language: ruby

rvm:
  - 2.5.0

services:
  - postgresql

before_script:
  - bundle install
  - psql -c 'create database pgapp_test;' -U postgres
  - bin/rails db:migrate
  
dist: trusty

script:
  - bundle exec rspec

deploy:
  provider: heroku
  api_key:
    secure: "IQVP0pPBLoGP/2zGj7HPcsZIovBFiTTPpYwnA7kbI4+RAytjXlDpSVWsCq77j5o1r26H3lVP0b91RPSPlcibpYhdE0hqZOSliDIbR689AXwcjYpLv724c5rt3a9S0nOG51siZwdmof6q9jVRyn7bk4G7ZoPzf8qtDXQ+oLyEvA7vGYlwBVj7kGojX7BeKjaT0L2Ph+wZIOVBV4I0Gli2k08qLqdOnYFdIw4N2ajFdl9C8DntLDJCA3scNQbKvJ0Z6ZuJ1grI5kTNwiCULRsb13LTo4oPzajgraoAiKeEOAuikzxqXFKPaGoq2hU5ywT697+hkzvPw7yfH2Es3NEvlr+JgAgAOHFHz3a8nXgoKh3E2yiH5LSmL8H0rGxl7u71naJC13a9S/uySiTmaJ7mHwYILj8bL1ulQp0j93Vz0Gahejqd3fe7PC0mNqgWh4Kb+UpAHgd89R4qOLrfpl1FZH5nqDUTdmvCJZFnx1Kinbw17Ib1Q9G7VbXM8FuK9rxy0EQno6EHj4VPRyl34783SFiS3M5pyjZFZr+iKl92IxlPEAasT4bnukG8CxldXfcTUVIMqTiugZD7EIOA9sdVXbPXD+6PQOc3ucxwFGiO2ihfCCbChaWyeBlw36NmqYC3P9E2bYA4YIe/j1lWZVZ3usf1eBFPDLswzVCYeL1hLQw="
  app: the-undefined-method
  on:
    repo: Kittaru87/acebook-theUndefinedMethod

