language: ruby
rvm:
- 2.5.0
services:
- postgresql
before_script:
- bundle install
- psql -c 'create database pgapp_test;' -U postgres
- bin/rails db:migrate
dist: trusty
script:
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: khfqJ1USwG4x/7tpt42/3f6vqXiHNSgGZU7/8YfigXE+f9bFQjEloREXjoC1cFwTEY/cqf/usn/xlG6rgBoI9ypchaPSLy3ycPX0N/Hciz0BZgdoWc1I6RODzmCQ8Foa1MA7daFMQsWpB22o/rnsUEG9NX/kpfTfkN43Qz8Nf4WktvPkh1CJ9aOptfjekUhpPFNBtp4ene5r0S1kLPFeTMmqLDDMNjH4qwcfeWTUE1xQ8cCHkRZrB2MJFWPS/d5SsxLyLzDTptASbrhLWYU1snfe2WgpH4MVrNneaLhUaeelgvWCQqvaHeQ3tIMXtiD5mNWVnYcIgFxcXbesYH2SL+um68mz+qkfrfqB/URWn/8g+pHA2WOtlIYFhgIqNLRSNFjcSLGRCbmWhSZLvoILGgz/P/TbnqNA85FYaj73TQ04sq8E/zqRcZnvtKg1CJyBTiMjHVnVWLI+YT6UItE/zohfzDoCBR70zf2CswCcAMk79GxvkdLw9uFGWOMN/HooDuvPH/AmaFNBJAJFxTMUMRlot0sb+Q/pEZuItzUPRgHA4cK8LN8OjWkeXSPk8jZR/1PDu4SQc2shCzlBPK2bVz0Ns5L6ImrRd4breBcjVgugLB5+nZU6vbBiENfiSzLr/kvXgm6bwuaFK18zP9JBQzWcfUsWj++Y1qJ3+66fOfM=
  app: the-undefined-method
  on:
    repo: Kittaru87/acebook-theUndefinedMethod
