language: ruby

rvm:
  - 2.5.0

services:
  - postgresql

before_script:
  - bundle install
  - psql -c 'create database pgapp_test;' -U postgres
  - bin/rails db:migrate
  
dist: trusty

script:
  - bundle exec rspec

deploy:
  provider: heroku
  api_key:
    secure: "YDQFaO4iW2bGBGUCEOtaylyDu+WZDbfzn80cVI3iagCTPcYqcrlXWzzCZBIzmu0CnmppMxHHfZEAol8C7FT8bKoV/jEha37wAlaNhTBC/kI+Hdoctb4LjLEhEZBBZWRvsAIZWMaz7hABR4ZE6QXIuVEGDdNUMI8XQKnUD3ysWxLQgW8RNe/TN6ggvqbvN9I+pVyhrVWBNhuyhOAM+B+fbFBAIbJUIBUXZ1WuQdCn4o4Cw2P6EsoL8XK7jXjbfmeAfLdTawT4OikmiykAci1LlAGmowM99mi9CRND7F4hTNHgbqgRrLkfE2TPXCx9IQ9aJc8W3YxjkgVf5tC4OkCF7oQIzOn9o9YM2i56S32Nfm7Hh2V6A+2U0JHPxL0Bcls8X56Nd78+scTyw/egkXw1DK6zDG/qIb/ZHHIOogH2VsxtRNEUnkPKQnKsVqchAjpamEaTXCuY+5ATdM9vkGpmewl2cW78urjX/iW3MiWltUdUsR0WoIpnUl+p2vm0jFKJ8s2Gd4+1MpHUvoO9D66GfMIWW4rFw9O6e9Un7ka2ppjwoQfxdOtnnX/xut3f3BJK2So9ibaWO8KLdpJGrRP9M7Z578zrJVaa0nZqTC0Q1cdBp5+FITlcH6qOrNbEmIBIf9XIaw0AvoIqTJziYUiVysH4m4raMUPEOmqt1PjSiZQ="
  app: the-undefined-method
  on:
    repo: Kittaru87/acebook-theUndefinedMethod

