language: ruby
rvm:
- 2.5.0
services:
- postgresql
before_script:
- bundle install
- psql -c 'create database pgapp_test;' -U postgres
- bin/rails db:migrate
dist: trusty
script:
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: m1UW2wUyy7zdEj7dkberw1JqXlznA0GkIeDgBbYt7a7hLMT9t2NsnKtREuQtJhKyGPAXdkdySeRA1hW20YKQiJoy+PDLLcCTjQaEvuI8nA1x9AEKA4Pkd9ltoBUa89mMdcdTyf6JrLBqjAU2TkYz2mJHbrnWp5OExdnae94G4O3amScfHOJvvqVC3n8nWFdMmkVKeCVzVm+6QUyZme7oRRnPhqCluTSdIHLywUfnY1mTp99bvNnRIqkb3D6H1HdbUDjKS7neMGz+z3E3b9Fk9UsbkTe176P+U6fbsJ7oQaauOznc6liDBRG7V3fsEdcRER1HICJVKY38vcTRE3imNPlJ2vbkvAWF5hfDePnIMNxQ4zb7t+PDkLPXImR9nMJaBVH28iVijeysXpKcN0UK/nTM1hWCX0BXlSNgxyEHcUZKVs1XOz+TTuZPU0zP169fu4sfcl5OAHjwngwzrLYX+mkLTLCWS3YktcVTgTJ20p77n8kiyluCDAiyjo3IqeoamsKEuPyYrBCvqVdLG44sbXQQIq2mVmFw8B7fbo9mn/DcIKit+Dk5iig5Y0lyMdPN8rO09SP7/bjekfAWsLriD43kkURKqzrvMxA4rakN1j6CqtrYiHLgCXq/ontxyef2sWifqXTpUqT9GkUHBIxSm2MMO8DU7CyX5Pndnx4gTjs=
  app: the-undefined-method
  on:
    repo: Kittaru87/acebook-theUndefinedMethod
