env:
  global:
    - CC_TEST_REPORTER_ID=ABC123
language: ruby
rvm:
- 2.5.0
services:
- postgresql
before_script:
- bundle install
- psql -c 'create database pgapp_test;' -U postgres
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
- bin/rails db:migrate
dist: trusty
script:
- bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  provider: heroku
  api_key:
    secure: pvUvCFgsJmSHGxmrXqfH1Egfb+GPpq8ni+61LIkEaX/g1J5AzOogKPQPnJ0iM21/DU2oK1Nf9NTtq8TKDg8lBbHky4AiaQMsFhBh4l0ewTN0GM2+MYJflmIugK+THi5bH8dX/lsn3Wx0BMJUgEFNwlDBOee6jTYghDjCOGJqE3C/zMZenpoPFs//f3lBw7ijjQiqCRMkyIt9PSyo9QjupUyqJ3hlVa6TNEPF3BNuNS/Bg1uf+PFfJ1PBq8t90B3hSf+/JsSl9jXP/AzONBeLgfnlNF8qdcm1B/zOE7//lnrTjGZdlS0EKj+NViAdDagCxa15ZG3ExuVABkSNCVYGhNvMckvdunEZYaQYkvYsz+7zG06/jmXts6h+YwiM7CF4oLg0zhmzAa5Hom7dKXyQwPke4Q0tV9MoIy9tg5dSXYulZ5m1N4KdTM4qKRzPrqBis+UHlWwGZFVFZiFXgh6V1ZeDJQjl/ByT0i9EW60tp/stiKj+gljmhjOaqzqHzai1e8Lui3LIMxn0ky24KDOQRkEcFX9flGaL+0fs1k+wTG0YYg3KfT8pkerjy5opuDWMwdwB3zNHSeBvumLDZcHB9lXUzx6WXMSusEhmqjHvJkSclnx1Du3qhyx4GHQw8lVJS6VrHkKox+HDwZ2snVgElPWJm1PvbqV6b8R4kkfJZe0=
  app: the-undefined-method
  on:
    repo: Kittaru87/acebook-theUndefinedMethod
