language: ruby
rvm:
- 2.5.0
services:
- postgresql
before_script:
- bundle install
- psql -c 'create database pgapp_test;' -U postgres
- bin/rails db:migrate
dist: trusty
script:
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: NZNnzRRoRguxG2UeWhUMp9eBiHRBEvPDcbt7PPya5W0wCeWeR+wQepPLdd2c6u8j5rMUpiOOW7cXxzDC06zmMkFHUDqMuNd51VILAPQfX7xSSrbuab97P2+99Bkda6FLeKDUUS1v+HrLpXhSG/rF+ap0P6rytFiZgquhL83sLofEyTWzHkfsAl2idDVOus9JFsngk0n2v5ijayXHKydaFH2BQmXh5PxupWp/bh2PcRZxs3ZckS/+YlZjrxuFXNcs2dDS3eJ7jcraz4tQG7vYGcFDFOBkb9V2Pb0ia3yzUy9OcVbt59Lppuew87J4WAFPwBPhgmDH/tZtAm/51Rf3mUHtyfMeVR4GUX6z+gh2sCicYQXjTa4rFEK1LD/19BL8RXZ6Nzj2i2u7WcjUtNOr3xcI+JgIggEaJVSVeeKflEfweQPoVphyQTYVapSbIn/VX7/daFuwQNSGfACaGg2QiXA9oUwYoA+ZF7wFBTB+7ri6zWxVaU/wj2EhQ7Um5Gx1E0i/Y9J7Ia2GZEKrY/DGREvhlXgwX11/A2ZjPfsBRoWm4GtBCsv6HWG6t2BVr+RqG/ySOCNAgLQC8UEybSC2cuPSB/cA88pJ1PZlrq1FCJ+wB8pKpS1lPFXkPyBFh8LX0zMG2Owinx9BFXzkq1o7X3iDbME2oigCXBNiqODD860=
  app: the-undefined-method
  on:
    repo: Kittaru87/acebook-theUndefinedMethod
