addons:
  code_climate:
    repo_token:
      secure: Oh4aT5to7HGSqjbrEIW9hffxHq1bXJAb8GYZ9PxV5OiSXkHoXE4RYbRF/7p+Bja4/UUjErag1q16V4EIdIxoNQkDFIkT/jhezI9wJXG9j5aOSKcI2nOjM+oOX58tDNJPtrRWXmDf5jgATtqdk7M7LBnZjhSPhlzDMG6i/YQVMT9Skj3iUKMoZ1tKbmdy1CY2cK7Nd8Eo2dN+Ym28EBt0BSMfHhT7D9F3objfBaH4TYinXwWokQRjXHF08Rk0a9PL1KoxleoxAD4rwTlKvNA8PusbkaER4EgJN/U8A4gB0zgK9HsNJi2s27wERCnGFFxTkOZH+IyfOM5VvqU4BncqAX3dpu4FXu8YxNcf6+PWqFIOgXohze5q3oObxd895TeT5wmFGuxtD2FaYxpwJBiXnuLOBAwXUQEdNRF6QavHD0iFrX5bzDRDt31oVwEJhNYQzC+uhMcENK4CFhCCuTZyV3bkh8/qCqCRizfyTYML7HuVKbgJRBJqTKyuCTmHdLzItsyA8DT6BbrIkL+S+WIJZN6Rih13s9Wzg2aMfiuLucqVBQ1lf5UrBXQ6WujKAv/zM1UCnpvOSwQCpobLr+5YLBjqBxiHwqN414tkQB6VykmA+7J8qIMXAC1tyKHpDdYWdpe6QdRy9u8R98DaDsQqO8OThYa3mnzXr+thTT7f4ow=
language: ruby
rvm:
- 2.5.0
services:
- postgresql
before_script:
- bundle install
- psql -c 'create database pgapp_test;' -U postgres
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
- bin/rails db:migrate
dist: trusty
script:
- bundle exec rspec
after_script:
  - vendor/bin/test-reporter
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  provider: heroku
  api_key:
    secure: pvUvCFgsJmSHGxmrXqfH1Egfb+GPpq8ni+61LIkEaX/g1J5AzOogKPQPnJ0iM21/DU2oK1Nf9NTtq8TKDg8lBbHky4AiaQMsFhBh4l0ewTN0GM2+MYJflmIugK+THi5bH8dX/lsn3Wx0BMJUgEFNwlDBOee6jTYghDjCOGJqE3C/zMZenpoPFs//f3lBw7ijjQiqCRMkyIt9PSyo9QjupUyqJ3hlVa6TNEPF3BNuNS/Bg1uf+PFfJ1PBq8t90B3hSf+/JsSl9jXP/AzONBeLgfnlNF8qdcm1B/zOE7//lnrTjGZdlS0EKj+NViAdDagCxa15ZG3ExuVABkSNCVYGhNvMckvdunEZYaQYkvYsz+7zG06/jmXts6h+YwiM7CF4oLg0zhmzAa5Hom7dKXyQwPke4Q0tV9MoIy9tg5dSXYulZ5m1N4KdTM4qKRzPrqBis+UHlWwGZFVFZiFXgh6V1ZeDJQjl/ByT0i9EW60tp/stiKj+gljmhjOaqzqHzai1e8Lui3LIMxn0ky24KDOQRkEcFX9flGaL+0fs1k+wTG0YYg3KfT8pkerjy5opuDWMwdwB3zNHSeBvumLDZcHB9lXUzx6WXMSusEhmqjHvJkSclnx1Du3qhyx4GHQw8lVJS6VrHkKox+HDwZ2snVgElPWJm1PvbqV6b8R4kkfJZe0=
  app: the-undefined-method
  on:
    repo: Kittaru87/acebook-theUndefinedMethod
