language: ruby
rvm:
- 2.5.0
services:
- postgresql
before_script:
- bundle install
- psql -c 'create database pgapp_test;' -U postgres
- bin/rails db:migrate
dist: trusty
script:
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: r569xCKj0RNPDUb4/YrasaiSCElYw9T5uoERgF5P8KX+bCWr75Jb+NsF97jmQYHLBjMlGSMU7F3YkDDbVVwFnrPu9ji44hgt6OEAtf9Am5tFpl4yXpXPs6xYpv53dU2gmBlFfTS+iH5fAoBq8ZISOtV7UIKTrYzfe6BkNZ3382u7M9/QlFJpegFpeDqvvdJyMNyq5w/DzgshiRWtHnxJf7V21z/3pq7o/XN571QLSxXQp0od1d4U1kOfoNqjdkc1ys9CjMiwvMm1XgE5VzPO6F7i2uwsEuT6aeAhwCEbRo7I5d/OAIrIJ37qrllhcELKf98Sc72YT2Lgx8mv11gq/YHLJofunwBFnNYqAe5t3b4Ilu0XiXffSg1kTkeMC+X9dSoPTAsqRvXFbUk0R1xEqB0vJdm564ndBtPNolzMkcJSBW8vQcnHceqJScR9ndVCTlNgYtoVwI96tf2d1es+jiekPDseCh9jWc8cfSLrsdi2tPXCHNKe88c5AscWtcUuVKZTzMrSm/6vtp7Jv+hLeLouWYmZbL03YhqSZja8YOhkXF5vRoNKC2bQcOrlAC31YskMeS0UVqRponsXoMjgljccds14uUM8GT/T2Hq5q84/Boom5bkgN+ckVBQw7yaRT9nUJUQvxGJfgaPBqaLkx8F+yOylFHK2OYrYaKqHGow=
  app: the-undefined-method
  on:
    repo: Kittaru87/acebook-theUndefinedMethod
